<?xml version="1.0" encoding="UTF-8"?>
<setting>
<title>改造されたe-typing(HACKED)</title>
<data></data>
<exampleLimit>15</exampleLimit>
<type>0</type>
<shuffle>1</shuffle>
<sns>1</sns>
<snsURL>https://tiame.xyz/</snsURL>
<tData>7</tData>
<score>0</score>
<ranking>0</ranking>
<result>1</result>
<sentence>2</sentence>
<kana>2</kana>
<timer>240</timer>
<msg>1</msg>
<gaPage>/keybo/typing/roman/trysc/other/osouji</gaPage>
<adRefresh>1</adRefresh>
<isClose>1</isClose>
<retryMiss>1</retryMiss>
</setting>